name: llm-26-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - jupyterlab
  - ipykernel
  - ipywidgets
  - jupyterlab_widgets
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - networkx
  - psutil
  - nbconvert
  - pip:
      - requests
      - regex
      - addict
      - spacy
      - spacy-pkuseg
      - tiktoken
      - datasets
      - transformers
      - huggingface_hub
      - modelscope
      - ollama-python